# Netlify configuration file

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_SKIP_COLLABORATIVE_PREVIEWS = "true"
  NETLIFY_SKIP_DRAWER = "true"
  DISABLE_NETLIFY_DRAWER = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
